-- Day 15

-- 1. Customer + Order Overview

SELECT c.cust_id, c.signup_date, c.channel, 
COUNT(CASE WHEN o.status = 'completed' THEN o.order_id END) AS total_completed_orders,
SUM(CASE WHEN o.status = 'completed' THEN o.order_amount END) AS total_revenue
FROM customers_d15 c LEFT JOIN orders_d15 o
ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.signup_date, c.channel;

-- 2. Active vs Inactive Customers

SELECT c.cust_id,
	CASE
    WHEN COUNT(CASE WHEN o.status = 'completed' THEN 1 END) >= 1 THEN 'Active'
    ELSE 'Inactive'
    END AS cust_classification
FROM customers_d15 c JOIN orders_d15 o
ON c.cust_id = o.cust_id
GROUP BY c.cust_id;

-- 3. Channel-wise Revenue Quality

WITH tr AS (
SELECT c.channel, COUNT(DISTINCT c.cust_id) AS no_of_customers, SUM(o.order_amount) AS total_revenue
FROM customers_d15 c LEFT JOIN orders_d15 o 
ON c.cust_id = o.cust_id
GROUP BY c.channel
)
SELECT channel, no_of_customers, total_revenue, ROUND(total_revenue / no_of_customers, 2) AS avg_revenue_per_customer
FROM tr;

-- 4. Retention Signal (Critical Thinking)

WITH first_order AS (
SELECT cust_id, MIN(DATE_FORMAT(order_date, '%Y-%m')) AS first_order_month
FROM orders_d15
WHERE status = 'completed'
GROUP BY cust_id
)
SELECT DISTINCT o.cust_id
FROM orders_d15 o
JOIN first_order f
ON o.cust_id = f.cust_id
WHERE o.status = 'completed'
	AND DATE_FORMAT(o.order_date, '%Y-%m') > f.first_order_month;


-- 1. Why is LEFT JOIN important when analyzing customers?

-- It gives all records from customers table so none of the details are skipped unlike in inner join which returns only those records whichare matched in all tables.alter

-- 2. If Paid users generate more revenue but churn faster, is Paid a good channel?

/* No, In the short term it could be a benefit as the revenue is getting generated but this churn will affect the long term growth of business as there is no loyalty of customers
as they are not returning.

-- 3.  What metric would you show leadership: revenue by channel or retention by channel — and why?

/* Both revenue by channel and retention by channel to give complete details of the income generated by each channel and the customers from each channel who are returning.
It will also help in planning the next moves considering which channel to invest for better revenue and growth in futre. */
